package com.bodha.service.ai;

/**
 * Pluggable abstraction for Large Language Model (LLM) providers (Module H).
 *
 * Decouples the business and personalization logic from specific AI vendors (Gemini, HuggingFace, etc.),
 * enabling seamless vendor switching and clean testing via development/mock implementations.
 */
public interface AiProvider {

    /**
     * Unique identifier for the provider (e.g., "mock", "gemini").
     */
    String getProviderName();

    /**
     * Checks whether the provider is active, properly credentialed, and reachable.
     */
    boolean isAvailable();

    /**
     * Sends prompt payloads to the LLM and returns the generated content string.
     *
     * @param systemPrompt Strict behavioral boundaries, persona, and output schema definition
     * @param userPrompt The domain task containing structured learner context
     * @return Raw text generated by the AI model (expected to conform to requested JSON schemas)
     */
    String generateContent(String systemPrompt, String userPrompt);
}
